#!/bin/bash
set -e
python setup.py develop
alembic -c production.ini/#blog_pyramid revision --autogenerate -m "init"
alembic -c production.ini#blog_pyramid  upgrade head
initialize_blog_pyramid_db development.ini
python runapp.py