"""category model

Revision ID: 9851aed33451
Revises: 2b10c563f1b4
Create Date: 2020-10-07 14:41:05.671433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9851aed33451'
down_revision = '2b10c563f1b4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_category_slug'))
    )
    op.create_table('posts_categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_posts_categories_category_id_category')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_posts_categories_post_id_posts'))
    )
    op.add_column('posts', sa.Column('slug', sa.String(length=40), nullable=True))
    op.create_unique_constraint(op.f('uq_posts_slug'), 'posts', ['slug'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_posts_slug'), 'posts', type_='unique')
    op.drop_column('posts', 'slug')
    op.drop_table('posts_categories')
    op.drop_table('category')
    # ### end Alembic commands ###
