"""author field in Post model

Revision ID: b9ad58071427
Revises: 71d2c94e0cb8
Create Date: 2020-10-22 18:08:31.510260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ad58071427'
down_revision = '71d2c94e0cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
